import { z } from 'zod'

import { phoneSchema } from '@/features/auth/schema'

export const cartItemSchema = z.object({
  foodId: z.string().cuid('Invalid menu item'),
  quantity: z.coerce.number().int().min(1, 'Quantity must be at least 1').max(50, 'Maximum 50 per item'),
  optionIds: z.array(z.string().cuid()).max(30).default([]),
  notes: z.string().trim().max(200, 'Keep notes under 200 characters').optional().or(z.literal('')),
})
export type CartItemInput = z.infer<typeof cartItemSchema>

export const tableEntrySchema = z.object({
  tableNumber: z
    .string()
    .trim()
    .min(1, 'Enter your table number')
    .max(10, 'That table number looks too long')
    .regex(/^[A-Za-z0-9-]+$/, 'Use letters and numbers only'),
})
export type TableEntryInput = z.infer<typeof tableEntrySchema>

/**
 * The checkout summary's input.
 *
 * Mirrors the item shape of `placeOrderSchema` including its 60-line cap: the
 * quote is unauthenticated and fans out per distinct dish, so it needs the same
 * ceiling as the order it precedes.
 */
export const quoteCartSchema = z.object({
  items: z
    .array(
      z.object({
        foodId: z.string().cuid(),
        quantity: z.coerce.number().int().min(1).max(50),
        optionIds: z.array(z.string().cuid()).max(20).default([]),
      }),
    )
    .max(60),
  couponCode: z.string().trim().max(40).optional().or(z.literal('')),
  phone: z.string().trim().max(30).optional().or(z.literal('')),
  /*
   * The QR menu this basket was built under (ar.md §15, §24).
   *
   * The PRINTED public code, never a row id: §25 says not to put internal
   * identifiers on a public path, and this one is typed into a client payload
   * that anybody can read. The server resolves it to an experience, scoped to
   * the tenant it just resolved, so a code from another restaurant resolves to
   * nothing rather than attributing an order across a tenant boundary.
   */
  qrCode: z.string().trim().max(32).optional().or(z.literal('')),
})

export const placeOrderSchema = z.object({
  /*
   * Optional, because not every code has a table behind it (ar.md §3).
   *
   * A card on table 6 sends one. A delivery leaflet or a takeaway counter has
   * no table to send, and the order that comes out is a TAKEAWAY rather than a
   * DINE_IN with nowhere to sit. When it is absent the BRANCH must be named
   * instead — the table is what usually decides which kitchen cooks, and
   * something has to.
   */
  tableId: z.string().cuid('Select a table').optional().or(z.literal('')),
  /*
   * The branch code from the QR (`?b=`), carried through the cart so the order
   * does not depend on a cookie surviving three page loads on somebody's phone.
   * Optional: a single-site restaurant's code has no `b`, and the cookie or the
   * default branch answers.
   */
  branchCode: z.string().trim().max(12).optional().or(z.literal('')),
  /*
   * Both optional, deliberately. The staff schema below has always allowed a
   * blank name and phone — "a cashier ringing up a walk-in coffee has no phone
   * number to type and should not have to invent one" — while the guest at
   * table 7, whose table the app already knows, was held to a stricter
   * standard. Guests typed 1234567 or gave up and waved at a waiter, and the
   * junk numbers then poisoned loyalty matching. A guest who WANTS their
   * points still types their real number; a blank means the order simply has
   * no customer record — nothing pools any more.
   */
  customerName: z.string().trim().max(60).optional().or(z.literal('')),
  customerPhone: z
    .string()
    .trim()
    .max(20)
    .optional()
    .or(z.literal(''))
    .refine((value) => !value || /^[+\d][\d\s-]{6,}$/.test(value), 'Enter a valid phone number'),
  customerEmail: z.string().trim().email('Enter a valid email').max(255).optional().or(z.literal('')),
  guestCount: z.coerce.number().int().min(1).max(50).optional(),
  notes: z.string().trim().max(300).optional().or(z.literal('')),
  couponCode: z.string().trim().toUpperCase().max(32).optional().or(z.literal('')),
  /*
   * No `redeemPoints` here. The guest cart never offers redemption, but the
   * field used to sit in this public schema anyway — so anyone could POST an
   * order with someone else's phone number and spend that person's points,
   * no verification anywhere. Spending points is a till operation, where a
   * person checks who is asking; the field lives on the staff schema below.
   */
  items: z.array(cartItemSchema).min(1, 'Your cart is empty').max(60, 'Too many items in one order'),
  /*
   * One id per cart, generated by the client. Makes placing an order idempotent:
   * a double tap or a retry after a dropped connection carries the same key and
   * gets back the order that already exists, rather than a second one that would
   * deduct another full set of ingredients.
   */
  idempotencyKey: z.string().trim().min(8).max(64).optional().or(z.literal('')),
  /*
   * The QR menu this basket was built under (ar.md §15, §24).
   *
   * The PRINTED public code, never a row id: §25 says not to put internal
   * identifiers on a public path, and this one is typed into a client payload
   * that anybody can read. The server resolves it to an experience, scoped to
   * the tenant it just resolved, so a code from another restaurant resolves to
   * nothing rather than attributing an order across a tenant boundary.
   */
  qrCode: z.string().trim().max(32).optional().or(z.literal('')),
  /*
   * Where a delivery is going, chosen from the owner's own list.
   *
   * An id rather than typed text, because this system has no map: the owner
   * writes the places food goes — "Boys Hostel", "Villa 2" — and the guest
   * picks one, so the rider reads the same words every time instead of twenty
   * spellings of the same building. Validated against the restaurant and the
   * branch on the server; the NAME is snapshotted onto the order beside the
   * id, so a renamed or retired location does not rewrite past deliveries.
   */
  deliveryLocationId: z.string().cuid().optional().or(z.literal('')),
})
export type PlaceOrderInput = z.infer<typeof placeOrderSchema>

/**
 * Staff-entered orders.
 *
 * Customer name and phone are relaxed to optional here. A guest ordering by QR
 * is identifying themselves, so the public schema rightly insists on both; a
 * cashier ringing up a walk-in coffee has no phone number to type and should
 * not have to invent one to take the money. The service fills a placeholder
 * name when none is given.
 */
export const staffOrderSchema = placeOrderSchema.extend({
  /*
   * A cashier's cart may carry a discount on each line (pro.A.md §10).
   *
   * Deliberately on the STAFF schema and not on `cartItemSchema`: a guest's
   * own cart posts through the same shape, and a discount a guest can name is
   * a discount a guest can give themselves. `DISCOUNT_APPLY` gates it in the
   * action, and the total is re-derived on the server either way.
   */
  items: z
    .array(
      cartItemSchema.extend({
        discount: z.coerce.number().int().min(0).max(100_000_00).default(0),
        discountReason: z.string().trim().max(160).optional().or(z.literal('')),
      }),
    )
    .min(1, 'Your cart is empty')
    .max(60, 'Too many items in one order'),
  type: z.enum(['DINE_IN', 'TAKEAWAY', 'DELIVERY', 'COUNTER']).default('DINE_IN'),
  tableId: z.string().cuid().optional().or(z.literal('')),
  customerName: z.string().trim().max(60).optional().or(z.literal('')),
  customerPhone: z.string().trim().max(20).optional().or(z.literal('')),
  /// Whose table it is, when a cashier rings up on a waiter's behalf.
  servedById: z.string().min(1).optional().or(z.literal('')),
  /**
   * Refuse this order if the table is held for a booking or its bill is being
   * settled. Sent by the WAITER's pad; the till never sets it.
   *
   * The two screens genuinely differ. A waiter stands at the table and should
   * not seat a party where a booking is held, nor add a dish to a bill the
   * guests have already asked for — both end in an argument at the table. A
   * cashier does exactly those things on purpose: overriding a reservation for
   * a walk-in is a manager's call, and adding a forgotten dessert to a bill
   * being settled is the till's ordinary work.
   *
   * Opt-in rather than opt-out so no existing caller changes behaviour by
   * being left alone, and so the exemption is something a screen has to ask
   * for rather than something it inherits.
   */
  enforceTableReady: z.coerce.boolean().default(false),
  /*
   * The counter this till is standing at.
   *
   * The POS scopes its menu, prices and tables to `?branch=`, but the order
   * write resolved the branch on its own from the top-bar switcher — so an
   * owner ringing up at Jaffna with the switcher on "All locations" filed the
   * sale against the DEFAULT branch. The ticket then appeared on another
   * kitchen's rail and the takings landed in another branch's books. The
   * screen sends where it is; the server still checks the user may reach it.
   */
  branchId: z.string().cuid().optional().or(z.literal('')),
  manualDiscount: z.coerce.number().int().min(0).default(0),
  redeemPoints: z.coerce.number().int().min(0).max(1_000_000).default(0),
})
export type StaffOrderInput = z.infer<typeof staffOrderSchema>

export const updateOrderStatusSchema = z.object({
  orderId: z.string().cuid(),
  /*
   * CANCELLED is not a status change — it is a money event. Cancelling through
   * here used to skip everything `cancelOrder` exists for: the paid-money
   * guard, the loyalty and coupon give-backs, the cancel reason, freeing the
   * table. One entry point for cancellation, and this is not it.
   */
  status: z.enum(['PENDING', 'ACCEPTED', 'PREPARING', 'READY', 'SERVED', 'COMPLETED']),
  note: z.string().trim().max(200).optional(),
  estimatedMinutes: z.coerce.number().int().min(0).max(240).optional(),
})
export type UpdateOrderStatusInput = z.infer<typeof updateOrderStatusSchema>

/** New dishes from the menu joining an existing order (aO.md §3). */
export const addGuestOrderItemsSchema = z.object({
  orderId: z.string().cuid(),
  items: z
    .array(
      z.object({
        foodId: z.string().cuid(),
        quantity: z.coerce.number().int().min(1).max(50),
        optionIds: z.array(z.string()).default([]),
        notes: z.string().trim().max(160).optional().or(z.literal('')),
      }),
    )
    .min(1)
    .max(20),
})
export type AddGuestOrderItemsInput = z.infer<typeof addGuestOrderItemsSchema>

export const updateGuestOrderItemsSchema = z.object({
  orderId: z.string().cuid(),
  items: z
    .array(
      z.object({
        itemId: z.string().cuid(),
        quantity: z.coerce.number().int().min(0).max(50),
      }),
    )
    .min(1)
    .max(60),
})
export type UpdateGuestOrderItemsInput = z.infer<typeof updateGuestOrderItemsSchema>

export const serveOrderSchema = z.object({
  orderId: z.string().cuid(),
})

export const cancelOrderSchema = z.object({
  orderId: z.string().cuid(),
  reason: z.string().trim().min(3, 'Give a short reason').max(200),
})
export type CancelOrderInput = z.infer<typeof cancelOrderSchema>

export const updateItemStatusSchema = z.object({
  orderId: z.string().cuid(),
  itemId: z.string().cuid(),
  // No CANCELLED: taking a line off a bill is `voidOrderItem` — a reason, a
  // recalculated total and returned stock — not a status flip that leaves the
  // guest charged for food the kitchen stopped cooking. No QUEUED either:
  // progress only moves forward (abc.md §6), and nothing ever sent it.
  status: z.enum(['PREPARING', 'READY', 'SERVED']),
})

/**
 * Item-level progress by quantity (abc.md §6): each update moves a line's
 * prepared and/or served counter to the given value. Counters only go up and
 * `served ≤ prepared ≤ quantity`; the service refuses anything else.
 */
export const progressItemsSchema = z.object({
  orderId: z.string().cuid(),
  updates: z
    .array(
      z
        .object({
          itemId: z.string().cuid(),
          preparedQty: z.number().int().min(0).max(1000).optional(),
          servedQty: z.number().int().min(0).max(1000).optional(),
        })
        .refine((u) => u.preparedQty !== undefined || u.servedQty !== undefined, {
          message: 'Say what moved: prepared, served, or both',
        }),
    )
    .min(1)
    .max(100),
})
export type ProgressItemsInput = z.infer<typeof progressItemsSchema>

export const serviceRequestSchema = z.object({
  tableId: z.string().cuid(),
  // CALL_WAITER is the guest's "call waiter" button (abc.md §7).
  type: z.enum(['CALL_WAITER', 'WATER', 'PLATES', 'BILL', 'HELP', 'CLEAN_TABLE']),
  note: z.string().trim().max(160).optional().or(z.literal('')),
})

/** A colleague calling a waiter to a table from the till, the KDS or the floor. */
export const callWaiterSchema = z.object({
  tableId: z.string().cuid(),
  note: z.string().trim().max(160).optional().or(z.literal('')),
})

export const serviceRequestIdSchema = z.object({ requestId: z.string().min(1) })
export type ServiceRequestInput = z.infer<typeof serviceRequestSchema>

export const orderFilterSchema = z.object({
  search: z.string().trim().max(80).optional(),
  status: z
    .enum(['ALL', 'PENDING', 'ACCEPTED', 'PREPARING', 'READY', 'SERVED', 'COMPLETED', 'CANCELLED'])
    .default('ALL'),
  paymentStatus: z.enum(['ALL', 'UNPAID', 'PARTIAL', 'PAID', 'REFUNDED', 'FAILED']).default('ALL'),
  type: z.enum(['ALL', 'DINE_IN', 'TAKEAWAY', 'DELIVERY', 'COUNTER']).default('ALL'),
  from: z.string().optional(),
  to: z.string().optional(),
  page: z.coerce.number().int().min(1).default(1),
  perPage: z.coerce.number().int().min(10).max(100).default(25),
})
export type OrderFilterInput = z.infer<typeof orderFilterSchema>

export const applyDiscountSchema = z.object({
  orderId: z.string().cuid(),
  amount: z.coerce.number().int().min(0),
  reason: z.string().trim().max(160).optional(),
})
