import { z } from 'zod'

import { cartItemSchema } from '@/features/orders/schema'

const restaurantIdSchema = z.object({ restaurantId: z.string().cuid() })

/**
 * The website's address. Blank means "not recorded"; anything else has to be
 * a real origin with its scheme, because Test Connection pings it and a bare
 * "mrchai.lk" is not something `fetch` can call.
 */
const websiteUrlField = z
  .string()
  .trim()
  .max(200)
  .optional()
  .or(z.literal(''))
  .refine(
    (value) => !value || /^https?:\/\/[^\s/]+/i.test(value),
    'Enter the full address, starting with https://',
  )

export const connectWebsiteSchema = restaurantIdSchema.extend({ websiteUrl: websiteUrlField })
export type ConnectWebsiteInput = z.infer<typeof connectWebsiteSchema>

export const websiteUrlSchema = connectWebsiteSchema
export const websiteRestaurantSchema = restaurantIdSchema

/**
 * An order placed by the restaurant's own website (websiteconnect.md).
 *
 * A sibling of `placeOrderSchema`, not a reuse of it: that one requires a
 * table and the guest flow hard-codes DINE_IN, neither of which a website
 * order has. The line items ARE shared — `cartItemSchema` — so a website
 * cannot describe a dish in any way the till would not accept.
 *
 * No `redeemPoints`, for the reason the guest schema gives: spending points is
 * a till operation, where a person checks who is asking.
 */
export const websiteOrderSchema = z
  .object({
    /** A branch id or code from GET /connection. Omitted: the default branch. */
    branch: z.string().trim().max(40).optional().or(z.literal('')),
    type: z.enum(['TAKEAWAY', 'DELIVERY']).default('TAKEAWAY'),
    customerName: z.string().trim().min(1, 'Who is the order for?').max(60),
    customerPhone: z
      .string()
      .trim()
      .max(20)
      .optional()
      .or(z.literal(''))
      .refine((value) => !value || /^[+\d][\d\s-]{6,}$/.test(value), 'Enter a valid phone number'),
    customerEmail: z.string().trim().email('Enter a valid email').max(255).optional().or(z.literal('')),
    /** Required for DELIVERY. Carried in the order's notes — see the service. */
    deliveryAddress: z.string().trim().max(300).optional().or(z.literal('')),
    notes: z.string().trim().max(300).optional().or(z.literal('')),
    couponCode: z.string().trim().toUpperCase().max(32).optional().or(z.literal('')),
    items: z
      .array(cartItemSchema)
      .min(1, 'The order has no items')
      .max(60, 'Too many items in one order'),
    /**
     * One id per checkout, generated by the website. A retry after a dropped
     * connection carries the same id and gets the order that already exists,
     * not a second one.
     */
    idempotencyKey: z.string().trim().min(8).max(64).optional().or(z.literal('')),
  })
  .superRefine((value, ctx) => {
    if (value.type === 'DELIVERY' && !value.deliveryAddress) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['deliveryAddress'],
        message: 'A delivery order needs an address',
      })
    }
  })
export type WebsiteOrderInput = z.infer<typeof websiteOrderSchema>
